# Generated by Django 3.1.6 on 2021-02-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.PositiveIntegerField(choices=[(1, 'Одобрено'), (2, 'Отказано'), (3, 'Временный отказ')]),
        ),
    ]
