# Generated by Django 3.1.6 on 2021-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210210_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к решению'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Авто'), (2, 'Потреб'), (3, 'Залог'), (4, 'Ипотека')], verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Одобрено'), (2, 'Отказано'), (3, 'Временный отказ')], null=True, verbose_name='Решение'),
        ),
    ]
