# Generated by Django 3.1.6 on 2021-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210211_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Потреб', 'Потреб'), ('Залог', 'Залог'), ('Ипотека', 'Ипотека')], max_length=10, verbose_name='Продукт'),
        ),
    ]
