# Generated by Django 3.1.6 on 2021-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210213_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='solution',
            field=models.CharField(choices=[('Одобрено', 'Одобрено'), ('Отказано', 'Отказано'), ('Временный отказ', 'Временный отказ')], max_length=15, verbose_name='Решение'),
        ),
    ]
